package com.springapp.entities;
// Generated Nov 14, 2016 12:02:28 AM by Hibernate Tools 4.3.1



/**
 * Assignments generated by hbm2java
 */
public class Assignments  implements java.io.Serializable {


     private int assignmentId;
     private String assignmentsDescription;
     private Integer classId;
     private Boolean exam;
     private double percentOfGrade;
     private Integer maximumPoints;

    public Assignments() {
    }

	
    public Assignments(int assignmentId) {
        this.assignmentId = assignmentId;
    }
    public Assignments(int assignmentId, String assignmentsDescription, Integer classId, Boolean exam, Float percentOfGrade, Integer maximumPoints) {
       this.assignmentId = assignmentId;
       this.assignmentsDescription = assignmentsDescription;
       this.classId = classId;
       this.exam = exam;
       this.percentOfGrade = percentOfGrade;
       this.maximumPoints = maximumPoints;
    }
   
    public int getAssignmentId() {
        return this.assignmentId;
    }
    
    public void setAssignmentId(int assignmentId) {
        this.assignmentId = assignmentId;
    }
    public String getAssignmentsDescription() {
        return this.assignmentsDescription;
    }
    
    public void setAssignmentsDescription(String assignmentsDescription) {
        this.assignmentsDescription = assignmentsDescription;
    }
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
    public Boolean getExam() {
        return this.exam;
    }
    
    public void setExam(Boolean exam) {
        this.exam = exam;
    }
    public double getPercentOfGrade() {
        return this.percentOfGrade;
    }
    
    public void setPercentOfGrade(double percentOfGrade) {
        this.percentOfGrade = percentOfGrade;
    }
    public Integer getMaximumPoints() {
        return this.maximumPoints;
    }
    
    public void setMaximumPoints(Integer maximumPoints) {
        this.maximumPoints = maximumPoints;
    }




}


