package com.springapp.entities;
// Generated Nov 14, 2016 12:02:28 AM by Hibernate Tools 4.3.1



/**
 * Departments generated by hbm2java
 */
public class Departments  implements java.io.Serializable {


     private int departmentId;
     private String departmentName;
     private Integer departmentNumber;
     private String departmentManager;
     private String departmentChairperson;

    public Departments() {
    }

	
    public Departments(int departmentId) {
        this.departmentId = departmentId;
    }
    public Departments(int departmentId, String departmentName, Integer departmentNumber, String departmentManager, String departmentChairperson) {
       this.departmentId = departmentId;
       this.departmentName = departmentName;
       this.departmentNumber = departmentNumber;
       this.departmentManager = departmentManager;
       this.departmentChairperson = departmentChairperson;
    }
   
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public Integer getDepartmentNumber() {
        return this.departmentNumber;
    }
    
    public void setDepartmentNumber(Integer departmentNumber) {
        this.departmentNumber = departmentNumber;
    }
    public String getDepartmentManager() {
        return this.departmentManager;
    }
    
    public void setDepartmentManager(String departmentManager) {
        this.departmentManager = departmentManager;
    }
    public String getDepartmentChairperson() {
        return this.departmentChairperson;
    }
    
    public void setDepartmentChairperson(String departmentChairperson) {
        this.departmentChairperson = departmentChairperson;
    }




}


