package com.springapp.entities;
// Generated Nov 14, 2016 12:02:28 AM by Hibernate Tools 4.3.1



/**
 * Instructors generated by hbm2java
 */
public class Instructors  implements java.io.Serializable {


     private int instructorId;
     private String instructor;
     private String emailName;
     private String phoneNumber;
     private String extension;

    public Instructors() {
    }

	
    public Instructors(int instructorId) {
        this.instructorId = instructorId;
    }
    public Instructors(int instructorId, String instructor, String emailName, String phoneNumber, String extension) {
       this.instructorId = instructorId;
       this.instructor = instructor;
       this.emailName = emailName;
       this.phoneNumber = phoneNumber;
       this.extension = extension;
    }
   
    public int getInstructorId() {
        return this.instructorId;
    }
    
    public void setInstructorId(int instructorId) {
        this.instructorId = instructorId;
    }
    public String getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(String instructor) {
        this.instructor = instructor;
    }
    public String getEmailName() {
        return this.emailName;
    }
    
    public void setEmailName(String emailName) {
        this.emailName = emailName;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }




}


