package com.springapp.entities;
// Generated Nov 14, 2016 12:02:28 AM by Hibernate Tools 4.3.1



/**
 * Studentsandclasses generated by hbm2java
 */
public class StudentsAndClasses  implements java.io.Serializable {


     private int studentClassId;
     private Integer classId;
     private Integer studentId;
     private String grade;

    public StudentsAndClasses() {
    }

	
    public StudentsAndClasses(int studentClassId) {
        this.studentClassId = studentClassId;
    }
    public StudentsAndClasses(int studentClassId, Integer classId, Integer studentId, String grade) {
       this.studentClassId = studentClassId;
       this.classId = classId;
       this.studentId = studentId;
       this.grade = grade;
    }
   
    public int getStudentClassId() {
        return this.studentClassId;
    }
    
    public void setStudentClassId(int studentClassId) {
        this.studentClassId = studentClassId;
    }
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }




}


